### PR TITLE
Added Explanation of Branch And Bound Approach for solving n-queen Problem in README section

### PR DESCRIPTION
**Pull request by SACHIN5SOS**

### CODE REVIEW

**Comment by trekhleb** [comment]
@SACHIN5SOS 
Thank you for suggestion to improve documentation.
If it would be convenient to you could you please actually implement branch and bound version of the algorithm?

**Comment by SACHIN5SOS** [comment]
@trekhleb I tried but unable to implement it.  Found some issues with my code. So that's why I added only explanation.

**Comment by trekhleb** [comment]
No problem @SACHIN5SOS 

I hope I'll have time to try to implement it. It is really interesting to do. And also there is no branch-and-bound examples in this repo so far. It would be nice to have one.

I think README needs to be updated if we have code examples for that. So I hope after me or someone else will implement Branch-and-Bound approach I'll push this information to README. 

But for now I'll close this PR just to keep REDMEs focused.

Anyways thank you for your code suggestion!

**Comment by SACHIN5SOS** [comment]
Yeah Sure @trekhleb .Branch and Bound is interesting and should be there in this awesome repo. Travelling salesman problem, n-queen and job-assignment with branch and bound can be discussed there. I am also trying to implement and work on them.

**Pull request closed without merging**
