### PR TITLE
Add few algos implementation

### PR DESCRIPTION
**Pull request by tapasweni-pathak**
This adds implementation of

- [X] Count set bits in a number
- [X] XOR without using XOR operator
- [X] Count bits to convert one number to another
- [X] Check if a number is power of 2
- [X] Multiply a number By 7
- [X] Find number of pairs with Pandigital Concatenation
- [X] Booth's multiplication
- [ ] Segment tree with alternating OR and XOR opertions
- [X] Karatsuba Multiplication
- [ ] TSP using Bitmasking and Dynamic Programming
- [X] Converting floating point to binary representation

using bitwise operators.

### CODE REVIEW

**Comment by trekhleb** [comment]
@tapasweni-pathak thank you very much for PR! But could you please make PRs to be more focused. Instead of creating PR for all function at once let's have separate PRs and thus separate discussions for each of the function you want to contribute. Meanwhile I'll close this PR. Waiting forward to see your next more focused ones!

**Comment by tapasweni-pathak** [comment]
@trekhleb thanks for the review, I have created per algo PRs from this PR

* https://github.com/trekhleb/javascript-algorithms/pull/152
* https://github.com/trekhleb/javascript-algorithms/pull/153
* https://github.com/trekhleb/javascript-algorithms/pull/154
* https://github.com/trekhleb/javascript-algorithms/pull/155
* https://github.com/trekhleb/javascript-algorithms/pull/156
* https://github.com/trekhleb/javascript-algorithms/pull/157
* https://github.com/trekhleb/javascript-algorithms/pull/158
* https://github.com/trekhleb/javascript-algorithms/pull/159

I'll complete adding few updates in the above PRs, add few more PRs from this PR and update this comment, please let me know if you want me to add more to the description of any of the PRs. Feel free to ignore merging any of the PRs, I just wanted to look at the structure of the repo so created few PRs; thanks for creating the repo super useful resource for someone who is new to algorithms and/or looking for an implementation using JavaScript.

**Comment by tapasweni-pathak** [comment]
@trekhleb thanks for the review, I have created per algo PRs from this PR

* https://github.com/trekhleb/javascript-algorithms/pull/152
* https://github.com/trekhleb/javascript-algorithms/pull/153
* https://github.com/trekhleb/javascript-algorithms/pull/154
* https://github.com/trekhleb/javascript-algorithms/pull/155
* https://github.com/trekhleb/javascript-algorithms/pull/156
* https://github.com/trekhleb/javascript-algorithms/pull/157
* https://github.com/trekhleb/javascript-algorithms/pull/158
* https://github.com/trekhleb/javascript-algorithms/pull/159

I'll complete adding few updates in the above PRs, add few more PRs from this PR and update this comment, please let me know if you want me to add more to the description of any of the PRs. Feel free to ignore merging any of the PRs, I just wanted to look at the structure of the repo so created few PRs; thanks for creating the repo great resource for someone who is new to algorithms and/or looking for an implementation using JavaScript.

**Comment by tapasweni-pathak** [comment]
@trekhleb thanks for the review, I have created per algo PRs from this PR

* https://github.com/trekhleb/javascript-algorithms/pull/152
* https://github.com/trekhleb/javascript-algorithms/pull/153
* https://github.com/trekhleb/javascript-algorithms/pull/154
* https://github.com/trekhleb/javascript-algorithms/pull/155
* https://github.com/trekhleb/javascript-algorithms/pull/156
* https://github.com/trekhleb/javascript-algorithms/pull/157
* https://github.com/trekhleb/javascript-algorithms/pull/158
* https://github.com/trekhleb/javascript-algorithms/pull/159

I'll complete adding few updates in the above PRs, add few more PRs from this PR's checklist and update this comment, please let me know if you want me to add more to the description of any of the PRs. Feel free to ignore merging any of the PRs, I just wanted to look at the structure of the repo so created few PRs; thanks for creating the repo, great resource for someone who is new to algorithms and/or looking for an implementation using JavaScript.

**Comment by tapasweni-pathak** [comment]
@trekhleb thanks for the review, I have created an algo per PR(s) from this PR

* https://github.com/trekhleb/javascript-algorithms/pull/152
* https://github.com/trekhleb/javascript-algorithms/pull/153
* https://github.com/trekhleb/javascript-algorithms/pull/154
* https://github.com/trekhleb/javascript-algorithms/pull/155
* https://github.com/trekhleb/javascript-algorithms/pull/156
* https://github.com/trekhleb/javascript-algorithms/pull/157
* https://github.com/trekhleb/javascript-algorithms/pull/158
* https://github.com/trekhleb/javascript-algorithms/pull/159

I'll complete adding few updates in the above PRs, add few more PRs from this PR's checklist and update this comment, please let me know if you want me to add more to the description of any of the PRs. Feel free to ignore merging any of the PRs, I just wanted to look at the structure of the repo so created few PRs; thanks for creating the repo, great resource for someone who is new to algorithms and/or looking for an implementation using JavaScript.

**Comment by tapasweni-pathak** [comment]
@trekhleb thanks for the review, I have created an algo per PR(s) from this PR

* https://github.com/trekhleb/javascript-algorithms/pull/152
* https://github.com/trekhleb/javascript-algorithms/pull/153
* https://github.com/trekhleb/javascript-algorithms/pull/154
* https://github.com/trekhleb/javascript-algorithms/pull/155
* https://github.com/trekhleb/javascript-algorithms/pull/156
* https://github.com/trekhleb/javascript-algorithms/pull/157
* https://github.com/trekhleb/javascript-algorithms/pull/158
* https://github.com/trekhleb/javascript-algorithms/pull/159

I'll complete adding few updates in the above PRs, add few more PRs from this PR's checklist and update this comment, please let me know if you want me to add more to the description of any of the PRs. Feel free to ignore merging any of the PRs, wanted to look at the structure of the repo so added few PRs; thanks for creating the repo, great resource for someone who is new to algorithms and/or looking for an implementation using JavaScript.

**Comment by tapasweni-pathak** [comment]
@trekhleb thanks for the review, I have created an algo per PR(s) from this PR

* https://github.com/trekhleb/javascript-algorithms/pull/152
* https://github.com/trekhleb/javascript-algorithms/pull/153
* https://github.com/trekhleb/javascript-algorithms/pull/154
* https://github.com/trekhleb/javascript-algorithms/pull/155
* https://github.com/trekhleb/javascript-algorithms/pull/156
* https://github.com/trekhleb/javascript-algorithms/pull/157
* https://github.com/trekhleb/javascript-algorithms/pull/158
* https://github.com/trekhleb/javascript-algorithms/pull/159

I'll complete adding few updates in the above PRs, add few more PRs from this PR's checklist and update this comment, please let me know if you want me to add more to the description of any of the PRs. Feel free to ignore merging any of the PRs, wanted to look at the structure of this repo so added few PRs; thanks for creating the repo, great resource for someone who is new to algorithms and/or looking for an implementation using JavaScript.

**Pull request closed without merging**
