### PR TITLE
Update factorialRecursive.js by checking the factorial of negative numbers at run time

### PR DESCRIPTION
**Pull request by njiddasalifu**
added a clear check for the factorial eveluation of negative numbers to avoid wrong answer at runtime.

### CODE REVIEW

**Comment by lazarljubenovic** [comment]
It's bad practice to return a string or a number and then inspect it. You should throw an error for invalid input instead.

**Comment by lazarljubenovic** [comment]
There's no such thing as "documen". Also, writing to the document is probably even worse than returning a string. You should throw an error instead.

**Comment by lazarljubenovic** [comment]
You're throwing a string instead of an error now.

**Comment by njiddasalifu** [comment]
take a look again.

**Review by olgunkaya — CHANGES_REQUESTED** [review]
Do you really need that last number > 1 control ? You already guaranteed there the number is bigger than 1

**Comment by njiddasalifu** [comment]
@olgunkaya ooh i see I will remove that. Actually the fisrt lines took care of that already.

**Pull request closed without merging**
